### ISSUE TITLE
Admin Portal with basic features like CRUD 

### ISSUE THREAD

**Issue by SuccessSureshP** [SeattleGiveCamp/SGC2017_QAFoodBank#22]

**Comment by ptressel** [comment]
This already works.  I didn't want to submit it while it still has local copies of the Javascript libraries, as those are about 1GB, and we likely have duplicate copies of them.  The proper thing to do is use a CDN.  For the API project, which also seemed to contain the same libraries, we decided during the hackathon to just leave them in, and not worry about using a CDN, but we acknowledged that was because we were in a hurry.  (More on this in our Discord chat.)

The current admin code, which is obsolete, is in my repo, https://github.com/ptressel/SGC2017_QAFoodBank.  It's obsolete because I believe I've found the actual documentation re. checkboxes and ASP.NET MVC.  ;-)  Hoping to test this tomorr...wait, I mean, later today.

So, do we want to ignore that 1GB worth of excess library?  As I explained during the event, we cannot remove it by deleting the files and committing the delete -- they will still be in the repo, as the repo contains the full history.  But we could, at some later time, do a "rewrite history" pass, and filter out those libraries, after we add the appropriate CDN requests.
